version: '3.8'

services:
  memory:
    image: memory
    build:
      context: ./
      target: dev
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    environment: 
      NODE_ENV: dev
    links: 
      - mongodb
  mongodb:
    image: mongo:latest
    ports: 
      - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data: