version: "3.8"

services:
  http:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - 8700:80
  memory:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3000:3000
